### ISSUE TITLE
now on rpi pico instead of esp8266 

### ISSUE THREAD

**Issue by thegreenlion42** [overflo23/MH-Z19_MicroPython#3]
now on rpi pico instead of esp8266... 

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "mhz19.py", line 56, in get_data
  File "mhz19.py", line 77, in crc8
IndexError: bytearray index out of range

**Comment by PID-and-Me** [comment]
Did you ever get it working on the pico?

**Comment by thegreenlion42** [comment]
Not with this library, to make the sensor work on the Pico I had to write my own code, based on this library and the documentation of the sensor.
